version: '3.4'
services:
  fd_server:
    image: lcas.lincoln.ac.uk/lcas/fd_server:latest
    build: 
      context: ..
      dockerfile: fd_webserver/Dockerfile
      network: host
    environment:
      - BASE_URL=http://lcas.lincoln.ac.uk/fast-downward/
    ports:
      - "5000:5000"
#    volumes:
#      - ./app.py:/fastdownward/app.py

